[package]
name = "kairo-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.9.5", features = ["serde"] }
walkdir = "2.5.0"
